name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [nightly, beta, stable, stable 18 months ago]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      name: Checkout Repo

    - uses: dtolnay/rust-toolchain@stable
      name: Install Rust ToolChain
      with:
        toolchain: ${{ matrix.rust }}

    - name: Build
      run: cargo build --verbose

